export const GOT_INSTANCE = "GOT_INSTANCE";
export const HTTP_AGENT_CONFIG = "HTTP_AGENT_CONFIG";
export const TRACE_DATA_SERVICE = "TRACE_DATA_SERVICE";
export const TRACE_SERVICE_CONFIG = "TRACE_SERVICE_CONFIG";
