export const GOT_INSTANCE = 'GOT_INSTANCE';
export const HTTP_CLIENT_SERVICE_CONFIG = 'HTTP_CLIENT_SERVICE_CONFIG';
export const TRACE_DATA_SERVICE = 'TRACE_DATA_SERVICE';
export const FOR_INSTANCE__GOT_OPTS = 'HTTP_CLIENT_FOR_INSTANCE_GOT_OPTS';
export const FOR_ROOT__GOT_OPTS = 'HTTP_CLIENT_FOR_ROOT_GOT_OPTS';
export const DEFAULT__GOT_OPTS = 'HTTP_CLIENT_DEFAULT_GOT_OPTS';
