export const GOT_INSTANCE = 'GOT_INSTANCE';
export const TRACE_DATA_SERVICE = 'TRACE_DATA_SERVICE';
export const DEFAULT__SERVICE_CONFIG = 'DEFAULT__SERVICE_CONFIG';
export const FOR_INSTANCE__SERVICE_CONFIG = 'FOR_INSTANCE__SERVICE_CONFIG';
export const FOR_ROOT__SERVICE_CONFIG = 'FOR_ROOT__SERVICE_CONFIG';
export const FOR_INSTANCE__GOT_OPTS = 'HTTP_CLIENT_FOR_INSTANCE_GOT_OPTS';
export const FOR_ROOT__GOT_OPTS = 'HTTP_CLIENT_FOR_ROOT_GOT_OPTS';
export const DEFAULT__GOT_OPTS = 'HTTP_CLIENT_DEFAULT_GOT_OPTS';
