export const GOT_INSTANCE = 'GOT_INSTANCE';
export const HTTP_CLIENT_SERVICE_CONFIG = 'HTTP_CLIENT_SERVICE_CONFIG';
export const TRACE_DATA_SERVICE = 'TRACE_DATA_SERVICE';
export const HTTP_CLIENT_ROOT_GOT_OPTS = 'HTTP_CLIENT_ROOT_GOT_OPTS';
export const HTTP_CLIENT_INSTANCE_GOT_OPTS = 'HTTP_CLIENT_INSTANCE_GOT_OPTS';
